const allLanguages = [
  { name: 'Grupo 1', group: 0 },
  { name: 'Inglês US', group: 0 },
  { name: 'Inglês UK', group: 0 },
  { name: 'Português BR', group: 0 },
  { name: 'Português PT', group: 0 },
  { name: 'Espanhol (ES)', group: 0 },
  { name: 'Espanhol (LATAM)', group: 0 },
  { name: 'Grupo 2', group: 1 },
  { name: 'Francês', group: 1 },
  { name: 'Franco-canadense', group: 1 },
  { name: 'Italiano', group: 1 },
  { name: 'Alemão', group: 1 },
  { name: 'Grupo 3', group: 2 },
  { name: 'Árabe', group: 2 },
  { name: 'Chinês (Mandarim Simplificado)', group: 2 },
  { name: 'Dinamarquês', group: 2 },
  { name: 'Finlandês', group: 2 },
  { name: 'Hebraico', group: 2 },
  { name: 'Holandês', group: 2 },
  { name: 'Islandês', group: 2 },
  { name: 'Japonês', group: 2 },
  { name: 'Norueguês', group: 2 },
  { name: 'Russo', group: 2 },
  { name: 'Sueco', group: 2 },
  { name: 'Tcheco', group: 2 },
  { name: 'Turco', group: 2 },
  { name: 'Polinês', group: 2 },
  { name: 'Grego', group: 2 },
  { name: 'Grupo 4', group: 3 },
  { name: 'Africâner', group: 3 },
  { name: 'Akan', group: 3 },
  { name: 'Albanês', group: 3 },
  { name: 'Amárico', group: 3 },
  { name: 'Armênio', group: 3 },
  { name: 'Assamês', group: 3 },
  { name: 'Assírio', group: 3 },
  { name: 'Azeri', group: 3 },
  { name: 'Bambara', group: 3 },
  { name: 'Basco', group: 3 },
  { name: 'Bashkir', group: 3 },
  { name: 'Bengalês', group: 3 },
  { name: 'Bielo - russo', group: 3 },
  { name: 'Birmanês', group: 3 },
  { name: 'Bósnio', group: 3 },
  { name: 'Bravanês', group: 3 },
  { name: 'Búlgaro', group: 3 },
  { name: 'Butanês', group: 3 },
  { name: 'Cambojano', group: 3 },
  { name: 'Canarês', group: 3 },
  { name: 'Canjobal', group: 3 },
  { name: 'Cantonês', group: 3 },
  { name: 'Catalão', group: 3 },
  { name: 'Caxemira', group: 3 },
  { name: 'Cazaque', group: 3 },
  { name: 'Cebuano', group: 3 },
  { name: 'Chaldean', group: 3 },
  { name: 'Chamorro', group: 3 },
  { name: 'Chaozhou', group: 3 },
  { name: 'Chavacano', group: 3 },
  { name: 'Chinês (Mandarim Tradicional)', group: 3 },
  { name: 'Chona', group: 3 },
  { name: 'Chuquês', group: 3 },
  { name: 'Cingalês', group: 3 },
  { name: 'Coreano', group: 3 },
  { name: 'Cree', group: 3 },
  { name: 'Croata', group: 3 },
  { name: 'Curdo', group: 3 },
  { name: 'Curmânji', group: 3 },
  { name: 'Dacota', group: 3 },
  { name: 'Dari', group: 3 },
  { name: 'Dinka', group: 3 },
  { name: 'Dioula', group: 3 },
  { name: 'Eslovaco', group: 3 },
  { name: 'Esloveno', group: 3 },
  { name: 'Estoniano', group: 3 },
  { name: 'Ewe', group: 3 },
  { name: 'Fanti', group: 3 },
  { name: 'Faroês', group: 3 },
  { name: 'Farsi', group: 3 },
  { name: 'Flamengo', group: 3 },
  { name: 'Frísio', group: 3 },
  { name: 'Fujian', group: 3 },
  { name: 'Fujianês', group: 3 },
  { name: 'Fula', group: 3 },
  { name: 'Fulani', group: 3 },
  { name: 'Fuzhou', group: 3 },
  { name: 'Gaélico', group: 3 },
  { name: 'Galego', group: 3 },
  { name: 'Galês', group: 3 },
  { name: 'Ganda', group: 3 },
  { name: 'Georgiano', group: 3 },
  { name: 'Gorani', group: 3 },
  { name: 'Guanxi', group: 3 },
  { name: 'Gujarati', group: 3 },
  { name: 'Hacá', group: 3 },
  { name: 'Haitiano', group: 3 },
  { name: 'Hassaniya', group: 3 },
  { name: 'Hauçá', group: 3 },
  { name: 'Hiligaynon', group: 3 },
  { name: 'Hindi', group: 3 },
  { name: 'Hindi fijiano', group: 3 },
  { name: 'Hmong', group: 3 },
  { name: 'Húngaro', group: 3 },
  { name: 'Ibanag', group: 3 },
  { name: 'Igbo', group: 3 },
  { name: 'Iídiche', group: 3 },
  { name: 'Ilocano', group: 3 },
  { name: 'Ilonggo', group: 3 },
  { name: 'Indiano', group: 3 },
  { name: 'Indonésio', group: 3 },
  { name: 'Inuktitut', group: 3 },
  { name: 'Iorubá', group: 3 },
  { name: 'Irlandês', group: 3 },
  { name: 'Jakartanese', group: 3 },
  { name: 'Javanês', group: 3 },
  { name: 'Karen', group: 3 },
  { name: 'Khalkha', group: 3 },
  { name: 'Khmer', group: 3 },
  { name: 'Kikuyu', group: 3 },
  { name: 'Kirundi', group: 3 },
  { name: 'Kosovo', group: 3 },
  { name: 'Kotokoli', group: 3 },
  { name: 'Krio', group: 3 },
  { name: 'Lakota', group: 3 },
  { name: 'Laociano', group: 3 },
  { name: 'Latim', group: 3 },
  { name: 'Letão', group: 3 },
  { name: 'Lingala', group: 3 },
  { name: 'Língua de sinais americana', group: 3 },
  { name: 'Lituano', group: 3 },
  { name: 'Luganda', group: 3 },
  { name: 'Luo', group: 3 },
  { name: 'Lusoga', group: 3 },
  { name: 'Luxemburguês', group: 3 },
  { name: 'Maay', group: 3 },
  { name: 'Macedônio', group: 3 },
  { name: 'Malaiala', group: 3 },
  { name: 'Malaio', group: 3 },
  { name: 'Maldivense', group: 3 },
  { name: 'Malgaxe', group: 3 },
  { name: 'Maltês', group: 3 },
  { name: 'Mandarim Tradicional', group: 3 },
  { name: 'Mandinga', group: 3 },
  { name: 'Mandinka', group: 3 },
  { name: 'Maori', group: 3 },
  { name: 'Marata', group: 3 },
  { name: 'Marshalês', group: 3 },
  { name: 'Mien', group: 3 },
  { name: 'Mirpuri', group: 3 },
  { name: 'Mixteco', group: 3 },
  { name: 'Moldovan', group: 3 },
  { name: 'Mongol', group: 3 },
  { name: 'Napolitano', group: 3 },
  { name: 'Navajo', group: 3 },
  { name: 'Nepali', group: 3 },
  { name: 'Nianja', group: 3 },
  { name: 'Nuer', group: 3 },
  { name: 'Ojíbua', group: 3 },
  { name: 'Oriá', group: 3 },
  { name: 'Oromo', group: 3 },
  { name: 'Osseta', group: 3 },
  { name: 'Pachto', group: 3 },
  { name: 'Pahari', group: 3 },
  { name: 'Pampangan', group: 3 },
  { name: 'Patoá', group: 3 },
  { name: 'Pothwari', group: 3 },
  { name: 'Pulaar', group: 3 },
  { name: 'Punjabi', group: 3 },
  { name: 'Putian', group: 3 },
  { name: 'Quechua', group: 3 },
  { name: 'Quiniaruanda', group: 3 },
  { name: 'Quirguiz', group: 3 },
  { name: 'Romanche', group: 3 },
  { name: 'Romani', group: 3 },
  { name: 'Romeno', group: 3 },
  { name: 'Rundi', group: 3 },
  { name: 'Samoano', group: 3 },
  { name: 'Sango', group: 3 },
  { name: 'Sânscrito', group: 3 },
  { name: 'Sérvio', group: 3 },
  { name: 'Sichuan', group: 3 },
  { name: 'Siciliano', group: 3 },
  { name: 'Sindi', group: 3 },
  { name: 'Somali', group: 3 },
  { name: 'Soninquê', group: 3 },
  { name: 'Sorâni', group: 3 },
  { name: 'Soto do sul', group: 3 },
  { name: 'Suaíle', group: 3 },
  { name: 'Suázi / suazilandês', group: 3 },
  { name: 'Sundanês', group: 3 },
  { name: 'Susu', group: 3 },
  { name: 'Sylheti', group: 3 },
  { name: 'Tadjique', group: 3 },
  { name: 'Tagalog', group: 3 },
  { name: 'Tailandês', group: 3 },
  { name: 'Taiwanês', group: 3 },
  { name: 'Tâmil', group: 3 },
  { name: 'Telugu', group: 3 },
  { name: 'Tibetano', group: 3 },
  { name: 'Tigrínia', group: 3 },
  { name: 'Tonga', group: 3 },
  { name: 'Tshiluba', group: 3 },
  { name: 'Tsonga', group: 3 },
  { name: 'Tswana', group: 3 },
  { name: 'Turcomeno', group: 3 },
  { name: 'Ucraniano', group: 3 },
  { name: 'Uigur', group: 3 },
  { name: 'Uolofe', group: 3 },
  { name: 'Urdu', group: 3 },
  { name: 'Uzbeque', group: 3 },
  { name: 'Venda', group: 3 },
  { name: 'Vietnamita', group: 3 },
  { name: 'Visayan', group: 3 },
  { name: 'Xangainês', group: 3 },
  { name: 'Xhosa', group: 3 },
  { name: 'Yao', group: 3 },
  { name: 'Yupik', group: 3 },
  { name: 'Zulu', group: 3 },
];

export default allLanguages;
